package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

import java.math.BigDecimal;
public class ByCountry {
  /* Tax amount */
  @JsonProperty("value")
  private BigDecimal value = null;
  /* Country name */
  @JsonProperty("tax_country_name")
  private String taxCountryName = null;
  /* Two letter ISO country code. */
  @JsonProperty("tax_country_code")
  private String taxCountryCode = null;
  /* Three-letter ISO currency code. */
  @JsonProperty("currency_code")
  private String currencyCode = null;
  @JsonProperty("value")
  public BigDecimal getValue() {
    return value;
  }

  @JsonProperty("value")
  public ByCountry setValue(BigDecimal value) {
    this.value = value;
    return this;
  }

  @JsonProperty("tax_country_name")
  public String getTaxCountryName() {
    return taxCountryName;
  }

  @JsonProperty("tax_country_name")
  public ByCountry setTaxCountryName(String taxCountryName) {
    this.taxCountryName = taxCountryName;
    return this;
  }

  @JsonProperty("tax_country_code")
  public String getTaxCountryCode() {
    return taxCountryCode;
  }

  @JsonProperty("tax_country_code")
  public ByCountry setTaxCountryCode(String taxCountryCode) {
    this.taxCountryCode = taxCountryCode;
    return this;
  }

  @JsonProperty("currency_code")
  public String getCurrencyCode() {
    return currencyCode;
  }

  @JsonProperty("currency_code")
  public ByCountry setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ByCountry {\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("  taxCountryName: ").append(taxCountryName).append("\n");
    sb.append("  taxCountryCode: ").append(taxCountryCode).append("\n");
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

