package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/


import java.math.BigDecimal;
import java.lang.Integer;
public class ByTaxationType {
  /* Number of taxed transactions. */
  private BigDecimal taxedCount = null;
  /* Number of tax deducted transactions. */
  private BigDecimal deductedCount = null;
  /* Total number of transactions */
  private BigDecimal transactionsCount = null;
  /* Total EU B2B transaction count. */
  private Integer euB2b = null;
  /* Total EU Taxed transaction count. */
  private Integer euTaxed = null;
  public BigDecimal getTaxedCount() {
    return taxedCount;
  }
  public ByTaxationType setTaxedCount(BigDecimal taxedCount) {
    this.taxedCount = taxedCount;
    return this;
  }

  public BigDecimal getDeductedCount() {
    return deductedCount;
  }
  public ByTaxationType setDeductedCount(BigDecimal deductedCount) {
    this.deductedCount = deductedCount;
    return this;
  }

  public BigDecimal getTransactionsCount() {
    return transactionsCount;
  }
  public ByTaxationType setTransactionsCount(BigDecimal transactionsCount) {
    this.transactionsCount = transactionsCount;
    return this;
  }

  public Integer getEuB2b() {
    return euB2b;
  }
  public ByTaxationType setEuB2b(Integer euB2b) {
    this.euB2b = euB2b;
    return this;
  }

  public Integer getEuTaxed() {
    return euTaxed;
  }
  public ByTaxationType setEuTaxed(Integer euTaxed) {
    this.euTaxed = euTaxed;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ByTaxationType {\n");
    sb.append("  taxedCount: ").append(taxedCount).append("\n");
    sb.append("  deductedCount: ").append(deductedCount).append("\n");
    sb.append("  transactionsCount: ").append(transactionsCount).append("\n");
    sb.append("  euB2b: ").append(euB2b).append("\n");
    sb.append("  euTaxed: ").append(euTaxed).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

