package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/


import java.util.*;
public class Country {
  /* Three letter ISO country code. */
  private String codeLong = null;
  /* Country ISO 3-digit code. */
  private String codenum = null;
  /* List of currencies. */
  private List<String> currency = new ArrayList<String>();
  /* True if tax calculation supported for this country. */
  private Boolean taxSupported = null;
  /* Country name. */
  private String name = null;
  /* Country ISO 3-digit code. */
  private String ccn3 = null;
  /* Three letter ISO country code. */
  private String cca3 = null;
  /* List of phone number calling codes. */
  private List<String> callingCode = new ArrayList<String>();
  /* VAT number country code. Important for Greece. */
  private String taxNumberCountryCode = null;
  /* Two letter ISO country code. */
  private String code = null;
  /* Two letter ISO country code. */
  private String cca2 = null;
  public String getCodeLong() {
    return codeLong;
  }
  public Country setCodeLong(String codeLong) {
    this.codeLong = codeLong;
    return this;
  }

  public String getCodenum() {
    return codenum;
  }
  public Country setCodenum(String codenum) {
    this.codenum = codenum;
    return this;
  }

  public List<String> getCurrency() {
    return currency;
  }
  public Country setCurrency(List<String> currency) {
    this.currency = currency;
    return this;
  }

  public Boolean getTaxSupported() {
    return taxSupported;
  }
  public Country setTaxSupported(Boolean taxSupported) {
    this.taxSupported = taxSupported;
    return this;
  }

  public String getName() {
    return name;
  }
  public Country setName(String name) {
    this.name = name;
    return this;
  }

  public String getCcn3() {
    return ccn3;
  }
  public Country setCcn3(String ccn3) {
    this.ccn3 = ccn3;
    return this;
  }

  public String getCca3() {
    return cca3;
  }
  public Country setCca3(String cca3) {
    this.cca3 = cca3;
    return this;
  }

  public List<String> getCallingCode() {
    return callingCode;
  }
  public Country setCallingCode(List<String> callingCode) {
    this.callingCode = callingCode;
    return this;
  }

  public String getTaxNumberCountryCode() {
    return taxNumberCountryCode;
  }
  public Country setTaxNumberCountryCode(String taxNumberCountryCode) {
    this.taxNumberCountryCode = taxNumberCountryCode;
    return this;
  }

  public String getCode() {
    return code;
  }
  public Country setCode(String code) {
    this.code = code;
    return this;
  }

  public String getCca2() {
    return cca2;
  }
  public Country setCca2(String cca2) {
    this.cca2 = cca2;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Country {\n");
    sb.append("  codeLong: ").append(codeLong).append("\n");
    sb.append("  codenum: ").append(codenum).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  taxSupported: ").append(taxSupported).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  ccn3: ").append(ccn3).append("\n");
    sb.append("  cca3: ").append(cca3).append("\n");
    sb.append("  callingCode: ").append(callingCode).append("\n");
    sb.append("  taxNumberCountryCode: ").append(taxNumberCountryCode).append("\n");
    sb.append("  code: ").append(code).append("\n");
    sb.append("  cca2: ").append(cca2).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

