package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

import com.taxamo.client.model.CountrySchema;
public class Countries {
  /* Country detected from SMS token */
  @JsonProperty("by_token")
  private CountrySchema byToken = null;
  /* Country detected by credit card number prefix */
  @JsonProperty("by_cc")
  private CountrySchema byCc = null;
  /* Used when merchant uses 2003 EU VAT rules. */
  @JsonProperty("by_2003_rules")
  private CountrySchema by2003Rules = null;
  /* Country forced by paramters */
  @JsonProperty("forced")
  private CountrySchema forced = null;
  /* Country detected by IP */
  @JsonProperty("by_ip")
  private CountrySchema byIp = null;
  /* Country guessed from IP due to lack of other evidence */
  @JsonProperty("guessed_from_ip")
  private CountrySchema guessedFromIp = null;
  /* Additional evidence held by the merchant. */
  @JsonProperty("other_commercially_relevant_info")
  private CountrySchema otherCommerciallyRelevantInfo = null;
  /* Country detected by billing country code */
  @JsonProperty("by_billing")
  private CountrySchema byBilling = null;
  /* Country detected from EU TAX number */
  @JsonProperty("by_tax_number")
  private CountrySchema byTaxNumber = null;
  /* Country detected from other evidence */
  @JsonProperty("detected")
  private CountrySchema detected = null;
  /* Self declared country as evidence. */
  @JsonProperty("self_declaration")
  private CountrySchema selfDeclaration = null;
  @JsonProperty("by_token")
  public CountrySchema getByToken() {
    return byToken;
  }
  
  @JsonProperty("by_token")
  public Countries setByToken(CountrySchema byToken) {
    this.byToken = byToken;
    return this;
  }

  @JsonProperty("by_cc")
  public CountrySchema getByCc() {
    return byCc;
  }
  
  @JsonProperty("by_cc")
  public Countries setByCc(CountrySchema byCc) {
    this.byCc = byCc;
    return this;
  }

  @JsonProperty("by_2003_rules")
  public CountrySchema getBy2003Rules() {
    return by2003Rules;
  }
  
  @JsonProperty("by_2003_rules")
  public Countries setBy2003Rules(CountrySchema by2003Rules) {
    this.by2003Rules = by2003Rules;
    return this;
  }

  @JsonProperty("forced")
  public CountrySchema getForced() {
    return forced;
  }
  
  @JsonProperty("forced")
  public Countries setForced(CountrySchema forced) {
    this.forced = forced;
    return this;
  }

  @JsonProperty("by_ip")
  public CountrySchema getByIp() {
    return byIp;
  }
  
  @JsonProperty("by_ip")
  public Countries setByIp(CountrySchema byIp) {
    this.byIp = byIp;
    return this;
  }

  @JsonProperty("guessed_from_ip")
  public CountrySchema getGuessedFromIp() {
    return guessedFromIp;
  }
  
  @JsonProperty("guessed_from_ip")
  public Countries setGuessedFromIp(CountrySchema guessedFromIp) {
    this.guessedFromIp = guessedFromIp;
    return this;
  }

  @JsonProperty("other_commercially_relevant_info")
  public CountrySchema getOtherCommerciallyRelevantInfo() {
    return otherCommerciallyRelevantInfo;
  }
  
  @JsonProperty("other_commercially_relevant_info")
  public Countries setOtherCommerciallyRelevantInfo(CountrySchema otherCommerciallyRelevantInfo) {
    this.otherCommerciallyRelevantInfo = otherCommerciallyRelevantInfo;
    return this;
  }

  @JsonProperty("by_billing")
  public CountrySchema getByBilling() {
    return byBilling;
  }
  
  @JsonProperty("by_billing")
  public Countries setByBilling(CountrySchema byBilling) {
    this.byBilling = byBilling;
    return this;
  }

  @JsonProperty("by_tax_number")
  public CountrySchema getByTaxNumber() {
    return byTaxNumber;
  }
  
  @JsonProperty("by_tax_number")
  public Countries setByTaxNumber(CountrySchema byTaxNumber) {
    this.byTaxNumber = byTaxNumber;
    return this;
  }

  @JsonProperty("detected")
  public CountrySchema getDetected() {
    return detected;
  }
  
  @JsonProperty("detected")
  public Countries setDetected(CountrySchema detected) {
    this.detected = detected;
    return this;
  }

  @JsonProperty("self_declaration")
  public CountrySchema getSelfDeclaration() {
    return selfDeclaration;
  }
  
  @JsonProperty("self_declaration")
  public Countries setSelfDeclaration(CountrySchema selfDeclaration) {
    this.selfDeclaration = selfDeclaration;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Countries {\n");
    sb.append("  byToken: ").append(byToken).append("\n");
    sb.append("  byCc: ").append(byCc).append("\n");
    sb.append("  by2003Rules: ").append(by2003Rules).append("\n");
    sb.append("  forced: ").append(forced).append("\n");
    sb.append("  byIp: ").append(byIp).append("\n");
    sb.append("  guessedFromIp: ").append(guessedFromIp).append("\n");
    sb.append("  otherCommerciallyRelevantInfo: ").append(otherCommerciallyRelevantInfo).append("\n");
    sb.append("  byBilling: ").append(byBilling).append("\n");
    sb.append("  byTaxNumber: ").append(byTaxNumber).append("\n");
    sb.append("  detected: ").append(detected).append("\n");
    sb.append("  selfDeclaration: ").append(selfDeclaration).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

