package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/


import java.math.BigDecimal;
public class CreateRefundOut {
  /* Total amount, including tax, to be refunded. Either amount or total amount is required. */
  private BigDecimal totalAmount = null;
  /* Calculated total amount. */
  private BigDecimal taxAmount = null;
  public BigDecimal getTotalAmount() {
    return totalAmount;
  }
  public CreateRefundOut setTotalAmount(BigDecimal totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

  public BigDecimal getTaxAmount() {
    return taxAmount;
  }
  public CreateRefundOut setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRefundOut {\n");
    sb.append("  totalAmount: ").append(totalAmount).append("\n");
    sb.append("  taxAmount: ").append(taxAmount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

