package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

import java.math.BigDecimal;
public class CreateRefundOut {
  /* Total amount, including tax, that was refunded in this call. */
  @JsonProperty("total_amount")
  private BigDecimal totalAmount = null;
  /* Calculated tax amount, that was refunded in this call. */
  @JsonProperty("tax_amount")
  private BigDecimal taxAmount = null;
  /* Total amount, including tax, that was refunded for this line. */
  @JsonProperty("refunded_total_amount")
  private BigDecimal refundedTotalAmount = null;
  /* Total tax amount, that was refunded for this line. */
  @JsonProperty("refunded_tax_amount")
  private BigDecimal refundedTaxAmount = null;
  @JsonProperty("total_amount")
  public BigDecimal getTotalAmount() {
    return totalAmount;
  }
  
  @JsonProperty("total_amount")
  public CreateRefundOut setTotalAmount(BigDecimal totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

  @JsonProperty("tax_amount")
  public BigDecimal getTaxAmount() {
    return taxAmount;
  }
  
  @JsonProperty("tax_amount")
  public CreateRefundOut setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
    return this;
  }

  @JsonProperty("refunded_total_amount")
  public BigDecimal getRefundedTotalAmount() {
    return refundedTotalAmount;
  }
  
  @JsonProperty("refunded_total_amount")
  public CreateRefundOut setRefundedTotalAmount(BigDecimal refundedTotalAmount) {
    this.refundedTotalAmount = refundedTotalAmount;
    return this;
  }

  @JsonProperty("refunded_tax_amount")
  public BigDecimal getRefundedTaxAmount() {
    return refundedTaxAmount;
  }
  
  @JsonProperty("refunded_tax_amount")
  public CreateRefundOut setRefundedTaxAmount(BigDecimal refundedTaxAmount) {
    this.refundedTaxAmount = refundedTaxAmount;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRefundOut {\n");
    sb.append("  totalAmount: ").append(totalAmount).append("\n");
    sb.append("  taxAmount: ").append(taxAmount).append("\n");
    sb.append("  refundedTotalAmount: ").append(refundedTotalAmount).append("\n");
    sb.append("  refundedTaxAmount: ").append(refundedTaxAmount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

