package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/


import com.taxamo.client.model.EvidenceSchema;
public class Evidence {
  /* Used when merchant uses 2003 EU VAT rules. */
  private EvidenceSchema by2003Rules = null;
  /* Country detected by payment method. */
  private EvidenceSchema byPaymentMethod = null;
  /* Country detected from EU TAX number */
  private EvidenceSchema byTaxNumber = null;
  /* Country detected by credit card number prefix */
  private EvidenceSchema byCc = null;
  /* Country detected by IP */
  private EvidenceSchema byIp = null;
  /* Country detected from SMS token */
  private EvidenceSchema byToken = null;
  /* Country detected by billing country code */
  private EvidenceSchema byBilling = null;
  /* Country guessed from IP due to lack of other evidence */
  private EvidenceSchema guessedFromIp = null;
  /* Country forced by paramters */
  private EvidenceSchema forced = null;
  public EvidenceSchema getBy2003Rules() {
    return by2003Rules;
  }
  public Evidence setBy2003Rules(EvidenceSchema by2003Rules) {
    this.by2003Rules = by2003Rules;
    return this;
  }

  public EvidenceSchema getByPaymentMethod() {
    return byPaymentMethod;
  }
  public Evidence setByPaymentMethod(EvidenceSchema byPaymentMethod) {
    this.byPaymentMethod = byPaymentMethod;
    return this;
  }

  public EvidenceSchema getByTaxNumber() {
    return byTaxNumber;
  }
  public Evidence setByTaxNumber(EvidenceSchema byTaxNumber) {
    this.byTaxNumber = byTaxNumber;
    return this;
  }

  public EvidenceSchema getByCc() {
    return byCc;
  }
  public Evidence setByCc(EvidenceSchema byCc) {
    this.byCc = byCc;
    return this;
  }

  public EvidenceSchema getByIp() {
    return byIp;
  }
  public Evidence setByIp(EvidenceSchema byIp) {
    this.byIp = byIp;
    return this;
  }

  public EvidenceSchema getByToken() {
    return byToken;
  }
  public Evidence setByToken(EvidenceSchema byToken) {
    this.byToken = byToken;
    return this;
  }

  public EvidenceSchema getByBilling() {
    return byBilling;
  }
  public Evidence setByBilling(EvidenceSchema byBilling) {
    this.byBilling = byBilling;
    return this;
  }

  public EvidenceSchema getGuessedFromIp() {
    return guessedFromIp;
  }
  public Evidence setGuessedFromIp(EvidenceSchema guessedFromIp) {
    this.guessedFromIp = guessedFromIp;
    return this;
  }

  public EvidenceSchema getForced() {
    return forced;
  }
  public Evidence setForced(EvidenceSchema forced) {
    this.forced = forced;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Evidence {\n");
    sb.append("  by2003Rules: ").append(by2003Rules).append("\n");
    sb.append("  byPaymentMethod: ").append(byPaymentMethod).append("\n");
    sb.append("  byTaxNumber: ").append(byTaxNumber).append("\n");
    sb.append("  byCc: ").append(byCc).append("\n");
    sb.append("  byIp: ").append(byIp).append("\n");
    sb.append("  byToken: ").append(byToken).append("\n");
    sb.append("  byBilling: ").append(byBilling).append("\n");
    sb.append("  guessedFromIp: ").append(guessedFromIp).append("\n");
    sb.append("  forced: ").append(forced).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

