package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

public class EvidenceSchema {
  /* If the evidence was used to match the actual country. */
  @JsonProperty("used")
  private Boolean used = null;
  /* Country code that was resolved using this evidence. */
  @JsonProperty("resolved_country_code")
  private String resolvedCountryCode = null;
  /* Type of evidence. */
  @JsonProperty("evidence_type")
  private String evidenceType = null;
  /* Value provided as evidence - for example IP address. */
  @JsonProperty("evidence_value")
  private String evidenceValue = null;
  @JsonProperty("used")
  public Boolean getUsed() {
    return used;
  }
  
  @JsonProperty("used")
  public EvidenceSchema setUsed(Boolean used) {
    this.used = used;
    return this;
  }

  @JsonProperty("resolved_country_code")
  public String getResolvedCountryCode() {
    return resolvedCountryCode;
  }
  
  @JsonProperty("resolved_country_code")
  public EvidenceSchema setResolvedCountryCode(String resolvedCountryCode) {
    this.resolvedCountryCode = resolvedCountryCode;
    return this;
  }

  @JsonProperty("evidence_type")
  public String getEvidenceType() {
    return evidenceType;
  }
  
  @JsonProperty("evidence_type")
  public EvidenceSchema setEvidenceType(String evidenceType) {
    this.evidenceType = evidenceType;
    return this;
  }

  @JsonProperty("evidence_value")
  public String getEvidenceValue() {
    return evidenceValue;
  }
  
  @JsonProperty("evidence_value")
  public EvidenceSchema setEvidenceValue(String evidenceValue) {
    this.evidenceValue = evidenceValue;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenceSchema {\n");
    sb.append("  used: ").append(used).append("\n");
    sb.append("  resolvedCountryCode: ").append(resolvedCountryCode).append("\n");
    sb.append("  evidenceType: ").append(evidenceType).append("\n");
    sb.append("  evidenceValue: ").append(evidenceValue).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

