package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

import java.util.*;
import com.taxamo.client.model.CurrencySchema;
public class GetCurrenciesDictOut {
  /* Currency dictionary. */
  @JsonProperty("dictionary")
  private List<CurrencySchema> dictionary = new ArrayList<CurrencySchema>();
  @JsonProperty("dictionary")
  public List<CurrencySchema> getDictionary() {
    return dictionary;
  }
  
  @JsonProperty("dictionary")
  public GetCurrenciesDictOut setDictionary(List<CurrencySchema> dictionary) {
    this.dictionary = dictionary;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCurrenciesDictOut {\n");
    sb.append("  dictionary: ").append(dictionary).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

