package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/


import java.util.*;
import com.taxamo.client.model.InputTransactionLine;
import com.taxamo.client.model.AdditionalCurrencies;
import com.taxamo.client.model.Evidence;
import com.taxamo.client.model.CustomFields;
import com.taxamo.client.model.InvoiceAddress;
public class InputTransactionUpdate {
  /* Invoice date of issue. */
  private String invoiceDate = null;
  /* Invoice address. */
  private InvoiceAddress invoiceAddress = null;
  /* Buyer's credit card prefix. */
  private String buyerCreditCardPrefix = null;
  /* Custom fields, stored as key-value pairs. This property is not processed and used mostly with Taxamo-built helpers. */
  private List<CustomFields> customFields = new ArrayList<CustomFields>();
  /* Additional currency information - can be used to receive additional information about invoice in another currency. */
  private AdditionalCurrencies additionalCurrencies = null;
  /*  Buyer's tax number - EU VAT number for example. If using EU VAT number, it is possible to provide country code in it (e.g. IE1234567X) or simply use billing_country_code field for that. In the first case, if billing_country_code value was provided, it will be overwritten with country code value extracted from VAT number - but only if the VAT has been verified properly. */
  private String buyerTaxNumber = null;
  /* Custom identifier provided upon transaction creation. */
  private String customId = null;
  /* Two-letter ISO country code, e.g. FR. This code applies to detected/set country for transaction, but can be set using manual mode. */
  private String taxCountryCode = null;
  /* Two-letter ISO country code, e.g. FR. Use it to force country code for tax calculation. */
  private String forceCountryCode = null;
  /* Buyer's declared email address. */
  private String buyerEmail = null;
  /* Use data and evidence from original transaction. Tax will be re-calculated, but evidence won't be re-checked. */
  private String originalTransactionKey = null;
  /* IP address of the buyer in dotted decimal (IPv4) or text format (IPv6). */
  private String buyerIp = null;
  /* Invoice place of issue. */
  private String invoicePlace = null;
  /* Verification token */
  private String verificationToken = null;
  /* True if the transaction deducted from tax and no tax is applied. Either set automatically when VAT number validates with VIES correctly, but can also be provided in manual mode. */
  private Boolean taxDeducted = null;
  /* Buyer's name - first name and last name or company name. */
  private String buyerName = null;
  /* Tax country of residence evidence. */
  private Evidence evidence = null;
  /* Custom data related to transaction. */
  private String customData = null;
  /* Billing two letter ISO country code. */
  private String billingCountryCode = null;
  /* Invoice number. */
  private String invoiceNumber = null;
  /* Currency code for transaction - e.g. EUR. */
  private String currencyCode = null;
  /* Transaction description. */
  private String description = null;
  /* Supply date in yyyy-MM-dd format. */
  private String supplyDate = null;
  /* Transaction lines. */
  private List<InputTransactionLine> transactionLines = new ArrayList<InputTransactionLine>();
  /* Order date in yyyy-MM-dd format, in merchant's timezone. If provided by the API caller, no timezone conversion is performed.
   Default value is current date and time. When using public token, the default value is used. */
  private String orderDate = null;
  public String getInvoiceDate() {
    return invoiceDate;
  }
  public InputTransactionUpdate setInvoiceDate(String invoiceDate) {
    this.invoiceDate = invoiceDate;
    return this;
  }

  public InvoiceAddress getInvoiceAddress() {
    return invoiceAddress;
  }
  public InputTransactionUpdate setInvoiceAddress(InvoiceAddress invoiceAddress) {
    this.invoiceAddress = invoiceAddress;
    return this;
  }

  public String getBuyerCreditCardPrefix() {
    return buyerCreditCardPrefix;
  }
  public InputTransactionUpdate setBuyerCreditCardPrefix(String buyerCreditCardPrefix) {
    this.buyerCreditCardPrefix = buyerCreditCardPrefix;
    return this;
  }

  public List<CustomFields> getCustomFields() {
    return customFields;
  }
  public InputTransactionUpdate setCustomFields(List<CustomFields> customFields) {
    this.customFields = customFields;
    return this;
  }

  public AdditionalCurrencies getAdditionalCurrencies() {
    return additionalCurrencies;
  }
  public InputTransactionUpdate setAdditionalCurrencies(AdditionalCurrencies additionalCurrencies) {
    this.additionalCurrencies = additionalCurrencies;
    return this;
  }

  public String getBuyerTaxNumber() {
    return buyerTaxNumber;
  }
  public InputTransactionUpdate setBuyerTaxNumber(String buyerTaxNumber) {
    this.buyerTaxNumber = buyerTaxNumber;
    return this;
  }

  public String getCustomId() {
    return customId;
  }
  public InputTransactionUpdate setCustomId(String customId) {
    this.customId = customId;
    return this;
  }

  public String getTaxCountryCode() {
    return taxCountryCode;
  }
  public InputTransactionUpdate setTaxCountryCode(String taxCountryCode) {
    this.taxCountryCode = taxCountryCode;
    return this;
  }

  public String getForceCountryCode() {
    return forceCountryCode;
  }
  public InputTransactionUpdate setForceCountryCode(String forceCountryCode) {
    this.forceCountryCode = forceCountryCode;
    return this;
  }

  public String getBuyerEmail() {
    return buyerEmail;
  }
  public InputTransactionUpdate setBuyerEmail(String buyerEmail) {
    this.buyerEmail = buyerEmail;
    return this;
  }

  public String getOriginalTransactionKey() {
    return originalTransactionKey;
  }
  public InputTransactionUpdate setOriginalTransactionKey(String originalTransactionKey) {
    this.originalTransactionKey = originalTransactionKey;
    return this;
  }

  public String getBuyerIp() {
    return buyerIp;
  }
  public InputTransactionUpdate setBuyerIp(String buyerIp) {
    this.buyerIp = buyerIp;
    return this;
  }

  public String getInvoicePlace() {
    return invoicePlace;
  }
  public InputTransactionUpdate setInvoicePlace(String invoicePlace) {
    this.invoicePlace = invoicePlace;
    return this;
  }

  public String getVerificationToken() {
    return verificationToken;
  }
  public InputTransactionUpdate setVerificationToken(String verificationToken) {
    this.verificationToken = verificationToken;
    return this;
  }

  public Boolean getTaxDeducted() {
    return taxDeducted;
  }
  public InputTransactionUpdate setTaxDeducted(Boolean taxDeducted) {
    this.taxDeducted = taxDeducted;
    return this;
  }

  public String getBuyerName() {
    return buyerName;
  }
  public InputTransactionUpdate setBuyerName(String buyerName) {
    this.buyerName = buyerName;
    return this;
  }

  public Evidence getEvidence() {
    return evidence;
  }
  public InputTransactionUpdate setEvidence(Evidence evidence) {
    this.evidence = evidence;
    return this;
  }

  public String getCustomData() {
    return customData;
  }
  public InputTransactionUpdate setCustomData(String customData) {
    this.customData = customData;
    return this;
  }

  public String getBillingCountryCode() {
    return billingCountryCode;
  }
  public InputTransactionUpdate setBillingCountryCode(String billingCountryCode) {
    this.billingCountryCode = billingCountryCode;
    return this;
  }

  public String getInvoiceNumber() {
    return invoiceNumber;
  }
  public InputTransactionUpdate setInvoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
    return this;
  }

  public String getCurrencyCode() {
    return currencyCode;
  }
  public InputTransactionUpdate setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

  public String getDescription() {
    return description;
  }
  public InputTransactionUpdate setDescription(String description) {
    this.description = description;
    return this;
  }

  public String getSupplyDate() {
    return supplyDate;
  }
  public InputTransactionUpdate setSupplyDate(String supplyDate) {
    this.supplyDate = supplyDate;
    return this;
  }

  public List<InputTransactionLine> getTransactionLines() {
    return transactionLines;
  }
  public InputTransactionUpdate setTransactionLines(List<InputTransactionLine> transactionLines) {
    this.transactionLines = transactionLines;
    return this;
  }

  public String getOrderDate() {
    return orderDate;
  }
  public InputTransactionUpdate setOrderDate(String orderDate) {
    this.orderDate = orderDate;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InputTransactionUpdate {\n");
    sb.append("  invoiceDate: ").append(invoiceDate).append("\n");
    sb.append("  invoiceAddress: ").append(invoiceAddress).append("\n");
    sb.append("  buyerCreditCardPrefix: ").append(buyerCreditCardPrefix).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("  additionalCurrencies: ").append(additionalCurrencies).append("\n");
    sb.append("  buyerTaxNumber: ").append(buyerTaxNumber).append("\n");
    sb.append("  customId: ").append(customId).append("\n");
    sb.append("  taxCountryCode: ").append(taxCountryCode).append("\n");
    sb.append("  forceCountryCode: ").append(forceCountryCode).append("\n");
    sb.append("  buyerEmail: ").append(buyerEmail).append("\n");
    sb.append("  originalTransactionKey: ").append(originalTransactionKey).append("\n");
    sb.append("  buyerIp: ").append(buyerIp).append("\n");
    sb.append("  invoicePlace: ").append(invoicePlace).append("\n");
    sb.append("  verificationToken: ").append(verificationToken).append("\n");
    sb.append("  taxDeducted: ").append(taxDeducted).append("\n");
    sb.append("  buyerName: ").append(buyerName).append("\n");
    sb.append("  evidence: ").append(evidence).append("\n");
    sb.append("  customData: ").append(customData).append("\n");
    sb.append("  billingCountryCode: ").append(billingCountryCode).append("\n");
    sb.append("  invoiceNumber: ").append(invoiceNumber).append("\n");
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  supplyDate: ").append(supplyDate).append("\n");
    sb.append("  transactionLines: ").append(transactionLines).append("\n");
    sb.append("  orderDate: ").append(orderDate).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

