package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

public class InvoiceAddress {
  /* Freeform address. Use when structured data is not available. Will be used in SAF-MOSS file if other fields are not provided. */
  @JsonProperty("freeform_address")
  private String freeformAddress = null;
  /* Building number. */
  @JsonProperty("building_number")
  private String buildingNumber = null;
  /*  Street name. */
  @JsonProperty("street_name")
  private String streetName = null;
  /* Address details - for example apartament number. */
  @JsonProperty("address_detail")
  private String addressDetail = null;
  /* City name. */
  @JsonProperty("city")
  private String city = null;
  /* Postal code. */
  @JsonProperty("postal_code")
  private String postalCode = null;
  /* Region, for United States - state code - e.g. NJ. */
  @JsonProperty("region")
  private String region = null;
  /* 2-letter ISO country code. */
  @JsonProperty("country")
  private String country = null;
  @JsonProperty("freeform_address")
  public String getFreeformAddress() {
    return freeformAddress;
  }
  
  @JsonProperty("freeform_address")
  public InvoiceAddress setFreeformAddress(String freeformAddress) {
    this.freeformAddress = freeformAddress;
    return this;
  }

  @JsonProperty("building_number")
  public String getBuildingNumber() {
    return buildingNumber;
  }
  
  @JsonProperty("building_number")
  public InvoiceAddress setBuildingNumber(String buildingNumber) {
    this.buildingNumber = buildingNumber;
    return this;
  }

  @JsonProperty("street_name")
  public String getStreetName() {
    return streetName;
  }
  
  @JsonProperty("street_name")
  public InvoiceAddress setStreetName(String streetName) {
    this.streetName = streetName;
    return this;
  }

  @JsonProperty("address_detail")
  public String getAddressDetail() {
    return addressDetail;
  }
  
  @JsonProperty("address_detail")
  public InvoiceAddress setAddressDetail(String addressDetail) {
    this.addressDetail = addressDetail;
    return this;
  }

  @JsonProperty("city")
  public String getCity() {
    return city;
  }
  
  @JsonProperty("city")
  public InvoiceAddress setCity(String city) {
    this.city = city;
    return this;
  }

  @JsonProperty("postal_code")
  public String getPostalCode() {
    return postalCode;
  }
  
  @JsonProperty("postal_code")
  public InvoiceAddress setPostalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  @JsonProperty("region")
  public String getRegion() {
    return region;
  }
  
  @JsonProperty("region")
  public InvoiceAddress setRegion(String region) {
    this.region = region;
    return this;
  }

  @JsonProperty("country")
  public String getCountry() {
    return country;
  }
  
  @JsonProperty("country")
  public InvoiceAddress setCountry(String country) {
    this.country = country;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoiceAddress {\n");
    sb.append("  freeformAddress: ").append(freeformAddress).append("\n");
    sb.append("  buildingNumber: ").append(buildingNumber).append("\n");
    sb.append("  streetName: ").append(streetName).append("\n");
    sb.append("  addressDetail: ").append(addressDetail).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  postalCode: ").append(postalCode).append("\n");
    sb.append("  region: ").append(region).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

