package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

import java.math.BigDecimal;
public class Refunds {
  /* Refund note image url. */
  @JsonProperty("refund_note_url")
  private String refundNoteUrl = null;
  /* Sequential refund note number. */
  @JsonProperty("refund_note_number")
  private String refundNoteNumber = null;
  /* Line identifier. If neither line key or custom id is provided, the refund amount will be assigned to lines in order. */
  @JsonProperty("line_key")
  private String lineKey = null;
  /* Refund timestamp in UTC timezone. */
  @JsonProperty("refund_timestamp")
  private String refundTimestamp = null;
  /* Amount, excluding tax, that was refunded. */
  @JsonProperty("amount")
  private BigDecimal amount = null;
  /* Was this refund applied to an informative line? */
  @JsonProperty("informative")
  private Boolean informative = null;
  /* Calculated tax amount, that was refunded. */
  @JsonProperty("tax_amount")
  private BigDecimal taxAmount = null;
  /* Tax rate for the line that was used for the refund calculation. */
  @JsonProperty("tax_rate")
  private BigDecimal taxRate = null;
  /* Total amount, including tax, that was refunded. */
  @JsonProperty("total_amount")
  private BigDecimal totalAmount = null;
  /* Refund reason, displayed on the credit note. */
  @JsonProperty("refund_reason")
  private String refundReason = null;
  @JsonProperty("refund_note_url")
  public String getRefundNoteUrl() {
    return refundNoteUrl;
  }

  @JsonProperty("refund_note_url")
  public Refunds setRefundNoteUrl(String refundNoteUrl) {
    this.refundNoteUrl = refundNoteUrl;
    return this;
  }

  @JsonProperty("refund_note_number")
  public String getRefundNoteNumber() {
    return refundNoteNumber;
  }

  @JsonProperty("refund_note_number")
  public Refunds setRefundNoteNumber(String refundNoteNumber) {
    this.refundNoteNumber = refundNoteNumber;
    return this;
  }

  @JsonProperty("line_key")
  public String getLineKey() {
    return lineKey;
  }

  @JsonProperty("line_key")
  public Refunds setLineKey(String lineKey) {
    this.lineKey = lineKey;
    return this;
  }

  @JsonProperty("refund_timestamp")
  public String getRefundTimestamp() {
    return refundTimestamp;
  }

  @JsonProperty("refund_timestamp")
  public Refunds setRefundTimestamp(String refundTimestamp) {
    this.refundTimestamp = refundTimestamp;
    return this;
  }

  @JsonProperty("amount")
  public BigDecimal getAmount() {
    return amount;
  }

  @JsonProperty("amount")
  public Refunds setAmount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  @JsonProperty("informative")
  public Boolean getInformative() {
    return informative;
  }

  @JsonProperty("informative")
  public Refunds setInformative(Boolean informative) {
    this.informative = informative;
    return this;
  }

  @JsonProperty("tax_amount")
  public BigDecimal getTaxAmount() {
    return taxAmount;
  }

  @JsonProperty("tax_amount")
  public Refunds setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
    return this;
  }

  @JsonProperty("tax_rate")
  public BigDecimal getTaxRate() {
    return taxRate;
  }

  @JsonProperty("tax_rate")
  public Refunds setTaxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
    return this;
  }

  @JsonProperty("total_amount")
  public BigDecimal getTotalAmount() {
    return totalAmount;
  }

  @JsonProperty("total_amount")
  public Refunds setTotalAmount(BigDecimal totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

  @JsonProperty("refund_reason")
  public String getRefundReason() {
    return refundReason;
  }

  @JsonProperty("refund_reason")
  public Refunds setRefundReason(String refundReason) {
    this.refundReason = refundReason;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Refunds {\n");
    sb.append("  refundNoteUrl: ").append(refundNoteUrl).append("\n");
    sb.append("  refundNoteNumber: ").append(refundNoteNumber).append("\n");
    sb.append("  lineKey: ").append(lineKey).append("\n");
    sb.append("  refundTimestamp: ").append(refundTimestamp).append("\n");
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  informative: ").append(informative).append("\n");
    sb.append("  taxAmount: ").append(taxAmount).append("\n");
    sb.append("  taxRate: ").append(taxRate).append("\n");
    sb.append("  totalAmount: ").append(totalAmount).append("\n");
    sb.append("  refundReason: ").append(refundReason).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

