package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/


import java.math.BigDecimal;
public class Report {
  /* Tax rate */
  private BigDecimal taxRate = null;
  /* Amount w/o tax */
  private BigDecimal amount = null;
  /* Country name */
  private String countryName = null;
  /* Two letter ISO country code. */
  private String countryCode = null;
  /* Tax amount */
  private BigDecimal taxAmount = null;
  /* If true, this line should not be entered into MOSS and is provided for informative purposes only. For example because the country is the same as MOSS registration country and merchant country. */
  private Boolean skipMoss = null;
  /* Three-letter ISO currency code. */
  private String currencyCode = null;
  public BigDecimal getTaxRate() {
    return taxRate;
  }
  public Report setTaxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
    return this;
  }

  public BigDecimal getAmount() {
    return amount;
  }
  public Report setAmount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  public String getCountryName() {
    return countryName;
  }
  public Report setCountryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

  public String getCountryCode() {
    return countryCode;
  }
  public Report setCountryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  public BigDecimal getTaxAmount() {
    return taxAmount;
  }
  public Report setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
    return this;
  }

  public Boolean getSkipMoss() {
    return skipMoss;
  }
  public Report setSkipMoss(Boolean skipMoss) {
    this.skipMoss = skipMoss;
    return this;
  }

  public String getCurrencyCode() {
    return currencyCode;
  }
  public Report setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Report {\n");
    sb.append("  taxRate: ").append(taxRate).append("\n");
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  countryName: ").append(countryName).append("\n");
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  taxAmount: ").append(taxAmount).append("\n");
    sb.append("  skipMoss: ").append(skipMoss).append("\n");
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

