package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/


import java.math.BigDecimal;
public class SettlementReportEntry {
  /* 3-letter ISO currency code for tax. */
  private String taxCurrencyCode = null;
  /* Tax country name */
  private String name = null;
  /* Tax amoount, in base currency. */
  private BigDecimal taxAmount = null;
  /* Foreign exchange rate used to convert to target currency. */
  private BigDecimal fxRate = null;
  /* Total amount, including tax, in base currency. */
  private BigDecimal totalAmount = null;
  /* Tax rate applied. */
  private BigDecimal taxRate = null;
  /* Amount, without tax, in base currency. */
  private BigDecimal amount = null;
  /* Tax amount in currency. */
  private BigDecimal taxAmountInCurrency = null;
  /* Original currency code. */
  private String currencyCode = null;
  public String getTaxCurrencyCode() {
    return taxCurrencyCode;
  }
  public SettlementReportEntry setTaxCurrencyCode(String taxCurrencyCode) {
    this.taxCurrencyCode = taxCurrencyCode;
    return this;
  }

  public String getName() {
    return name;
  }
  public SettlementReportEntry setName(String name) {
    this.name = name;
    return this;
  }

  public BigDecimal getTaxAmount() {
    return taxAmount;
  }
  public SettlementReportEntry setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
    return this;
  }

  public BigDecimal getFxRate() {
    return fxRate;
  }
  public SettlementReportEntry setFxRate(BigDecimal fxRate) {
    this.fxRate = fxRate;
    return this;
  }

  public BigDecimal getTotalAmount() {
    return totalAmount;
  }
  public SettlementReportEntry setTotalAmount(BigDecimal totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

  public BigDecimal getTaxRate() {
    return taxRate;
  }
  public SettlementReportEntry setTaxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
    return this;
  }

  public BigDecimal getAmount() {
    return amount;
  }
  public SettlementReportEntry setAmount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  public BigDecimal getTaxAmountInCurrency() {
    return taxAmountInCurrency;
  }
  public SettlementReportEntry setTaxAmountInCurrency(BigDecimal taxAmountInCurrency) {
    this.taxAmountInCurrency = taxAmountInCurrency;
    return this;
  }

  public String getCurrencyCode() {
    return currencyCode;
  }
  public SettlementReportEntry setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettlementReportEntry {\n");
    sb.append("  taxCurrencyCode: ").append(taxCurrencyCode).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  taxAmount: ").append(taxAmount).append("\n");
    sb.append("  fxRate: ").append(fxRate).append("\n");
    sb.append("  totalAmount: ").append(totalAmount).append("\n");
    sb.append("  taxRate: ").append(taxRate).append("\n");
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  taxAmountInCurrency: ").append(taxAmountInCurrency).append("\n");
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

