package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

public class UsTaxId {
  /* Tax id type. */
  @JsonProperty("tax_id_type")
  private String taxIdType = null;
  /* Tax ID */
  @JsonProperty("tax_id")
  private String taxId = null;
  /* State of issue */
  @JsonProperty("state_of_issue")
  private String stateOfIssue = null;
  @JsonProperty("tax_id_type")
  public String getTaxIdType() {
    return taxIdType;
  }
  
  @JsonProperty("tax_id_type")
  public UsTaxId setTaxIdType(String taxIdType) {
    this.taxIdType = taxIdType;
    return this;
  }

  @JsonProperty("tax_id")
  public String getTaxId() {
    return taxId;
  }
  
  @JsonProperty("tax_id")
  public UsTaxId setTaxId(String taxId) {
    this.taxId = taxId;
    return this;
  }

  @JsonProperty("state_of_issue")
  public String getStateOfIssue() {
    return stateOfIssue;
  }
  
  @JsonProperty("state_of_issue")
  public UsTaxId setStateOfIssue(String stateOfIssue) {
    this.stateOfIssue = stateOfIssue;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsTaxId {\n");
    sb.append("  taxIdType: ").append(taxIdType).append("\n");
    sb.append("  taxId: ").append(taxId).append("\n");
    sb.append("  stateOfIssue: ").append(stateOfIssue).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

