package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

public class UsTaxExemptState {
  /* Two character state abbreviation. */
  @JsonProperty("state_abbr")
  private String stateAbbr = null;
  /* Exemption reason */
  @JsonProperty("reason_for_exemption")
  private String reasonForExemption = null;
  /* Identifier for exemption reason. */
  @JsonProperty("identifier_for_exemption_reason")
  private String identifierForExemptionReason = null;
  @JsonProperty("state_abbr")
  public String getStateAbbr() {
    return stateAbbr;
  }

  @JsonProperty("state_abbr")
  public UsTaxExemptState setStateAbbr(String stateAbbr) {
    this.stateAbbr = stateAbbr;
    return this;
  }

  @JsonProperty("reason_for_exemption")
  public String getReasonForExemption() {
    return reasonForExemption;
  }

  @JsonProperty("reason_for_exemption")
  public UsTaxExemptState setReasonForExemption(String reasonForExemption) {
    this.reasonForExemption = reasonForExemption;
    return this;
  }

  @JsonProperty("identifier_for_exemption_reason")
  public String getIdentifierForExemptionReason() {
    return identifierForExemptionReason;
  }

  @JsonProperty("identifier_for_exemption_reason")
  public UsTaxExemptState setIdentifierForExemptionReason(String identifierForExemptionReason) {
    this.identifierForExemptionReason = identifierForExemptionReason;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsTaxExemptState {\n");
    sb.append("  stateAbbr: ").append(stateAbbr).append("\n");
    sb.append("  reasonForExemption: ").append(reasonForExemption).append("\n");
    sb.append("  identifierForExemptionReason: ").append(identifierForExemptionReason).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

