package com.taxamo.client.model;

/*
*  Copyright 2014 Taxamo, Ltd.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

/*
* NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
*/

import com.owlike.genson.annotation.JsonProperty;

public class ValidateTaxNumberOut {
  /* If the transaction is in a country supported by Taxamo, but the tax is not calculated due to merchant settings or EU B2B transaction for example. */
  @JsonProperty("tax_deducted")
  private Boolean taxDeducted = null;
  /*  Buyer's tax number - EU VAT number for example. If using EU VAT number, it is possible to provide country code in it (e.g. IE1234567X) or simply use billing_country_code field for that. In the first case, if billing_country_code value was provided, it will be overwritten with country code value extracted from VAT number - but only if the VAT has been verified properly. */
  @JsonProperty("buyer_tax_number")
  private String buyerTaxNumber = null;
  /* If the buyer tax number has been provided and was validated successfully. Always true for domestic transactions (billing country same as merchant's country), tax number doesn't get validated in that case. */
  @JsonProperty("buyer_tax_number_valid")
  private Boolean buyerTaxNumberValid = null;
  /* Billing two letter ISO country code. */
  @JsonProperty("billing_country_code")
  private String billingCountryCode = null;
  @JsonProperty("tax_deducted")
  public Boolean getTaxDeducted() {
    return taxDeducted;
  }

  @JsonProperty("tax_deducted")
  public ValidateTaxNumberOut setTaxDeducted(Boolean taxDeducted) {
    this.taxDeducted = taxDeducted;
    return this;
  }

  @JsonProperty("buyer_tax_number")
  public String getBuyerTaxNumber() {
    return buyerTaxNumber;
  }

  @JsonProperty("buyer_tax_number")
  public ValidateTaxNumberOut setBuyerTaxNumber(String buyerTaxNumber) {
    this.buyerTaxNumber = buyerTaxNumber;
    return this;
  }

  @JsonProperty("buyer_tax_number_valid")
  public Boolean getBuyerTaxNumberValid() {
    return buyerTaxNumberValid;
  }

  @JsonProperty("buyer_tax_number_valid")
  public ValidateTaxNumberOut setBuyerTaxNumberValid(Boolean buyerTaxNumberValid) {
    this.buyerTaxNumberValid = buyerTaxNumberValid;
    return this;
  }

  @JsonProperty("billing_country_code")
  public String getBillingCountryCode() {
    return billingCountryCode;
  }

  @JsonProperty("billing_country_code")
  public ValidateTaxNumberOut setBillingCountryCode(String billingCountryCode) {
    this.billingCountryCode = billingCountryCode;
    return this;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateTaxNumberOut {\n");
    sb.append("  taxDeducted: ").append(taxDeducted).append("\n");
    sb.append("  buyerTaxNumber: ").append(buyerTaxNumber).append("\n");
    sb.append("  buyerTaxNumberValid: ").append(buyerTaxNumberValid).append("\n");
    sb.append("  billingCountryCode: ").append(billingCountryCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}

